- name: install redis
  yum: pkg=redis state=present
  tags: redis

- name: set address
  replace: dest=/etc/redis.conf regexp='bind 127.0.0.1' replace='bind 0.0.0.0'
  tags: redis

- name: set port
  replace: dest=/etc/redis.conf regexp='port 6379' replace='port 13609'
  tags: redis

- name: set password
  replace: dest=/etc/redis.conf regexp='# requirepass foobared' replace='requirepass {{ password }}'
  tags: redis

- name: redis start on boot
  service: name=redis state=started enabled=yes
  tags: redis
