- name: install redis
  yum: pkg=redis state=present
  tags: redis

- name: set address
  replace: dest=/etc/redis.conf regexp='bind 127.0.0.1' replace='bind {{ redis.addr }}'
  tags: redis

- name: set port
  replace: dest=/etc/redis.conf regexp='port 6379' replace='port {{ redis.port }}'
  tags: redis

- name: set password
  replace: dest=/etc/redis.conf regexp='# requirepass foobared' replace='requirepass {{ redis.password }}'
  tags: redis

- name: redis start on boot
  service: name=redis state=started enabled=yes
  tags: redis
