- hosts: sakura_vps
  become: true
  tasks:
    - command: echo "$PATH"
      register: default_path

- hosts: sakura_vps
  become: true
  roles:
    - common
    - git
    - mysql
    - ruby
    - nginx
    - redis
    - ssh
    - firewall
  handlers:
    - name: restart sshd and firewalld
      action: service name={{ item }} state=restarted
      with_items: ["sshd", "firewalld"]
  environment:
    PATH: /usr/local/bin:{{ default_path.stdout }}
