- hosts: sakura_vps
  become: true
  tasks:
    - command: echo "$PATH"
      register: default_path

- hosts: sakura_vps
  become: true
  roles:
    - common
    - git
    - mysql
    - ruby
    - nginx
    - redis
    - ssh
    - firewall
  environment:
    PATH: /usr/local/bin:{{ default_path.stdout }}

