- name: add a user
  user: name={{ ssh.user }} state=present group=wheel password={{ ssh.password }}
  tags: ssh

- name: add a sudo user
  lineinfile: 'dest=/etc/sudoers backup=yes state=present regexp="^utahta" line="utahta ALL=(ALL) NOPASSWD: ALL"'
  tags: ssh

- name: set authorized_key
  authorized_key: user={{ ssh.user }} key="{{ ssh.authorized_key }}"
  tags: ssh

- name: set Port
  replace: dest=/etc/ssh/sshd_config regexp='#Port 22' replace='Port {{ ssh.port }}'
  tags: ssh

- name: set PermitRootLogin no
  replace: dest=/etc/ssh/sshd_config regexp='#PermitRootLogin yes' replace='PermitRootLogin no'
  tags: ssh

- name: set PasswordAuthentication no
  replace: dest=/etc/ssh/sshd_config regexp='PasswordAuthentication yes' replace='PasswordAuthentication no'
  tags: ssh
