- name: firewalld is enabled and started
  service: name=firewalld state=started enabled=yes
  tags: firewall

- name: firewalld enabled http
  firewalld: service=http permanent=true state=enabled
  notify: restart sshd and firewalld
  tags: firewall

- name: firewalld enabled https
  firewalld: service=https permanent=true state=enabled
  notify: restart sshd and firewalld
  tags: firewall

- name: firewalld enabled redis
  firewalld: port={{ redis.port }}/tcp permanent=true state=enabled
  notify: restart sshd and firewalld
  tags: firewall

- name: firewalld enabled ssh
  firewalld: port={{ ssh.port }}/tcp permanent=true state=enabled
  notify: restart sshd and firewalld
  tags: firewall

- name: firewalld disabled ssh
  firewalld: service=ssh permanent=true state=disabled
  notify: restart sshd and firewalld
  tags: firewall
