- name: clear ansible cache directory
  file: path=/tmp/ansible state=absent
- name: create ansible cache directory
  file: path=/tmp/ansible state=directory

- selinux: state=disabled

- include: yum.yml
- include: zsh.yml
- include: ntp.yml

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - vim-common
    - vim-enhanced
    - wget
